# Generated by Django 5.1.6 on 2025-03-08 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_activity_completed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "points_needed",
                    models.IntegerField(
                        default=0, help_text="Points required to redeem this reward"
                    ),
                ),
                (
                    "redeemed_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who have redeemed this reward",
                        related_name="redeemed_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
